=== pouncilt/ws-spring-restful-demo/src/main/resources/schemas/jaxb-intros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:jaxb-intros="http://www.jboss.org/xsd/jaxb/intros"
        targetNamespace="http://www.jboss.org/xsd/jaxb/intros"
        elementFormDefault="qualified">

    <xsd:element name="jaxb-intros">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">The jbossesb JAXB Annotation Introductions configuration.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="jaxb-intros:Class" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="default-namespace" use="optional"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Class">
        <xsd:sequence>
            <xsd:element ref="jaxb-intros:XmlAccessorType" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:XmlType" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:XmlRootElement" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:XmlTransient" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:XmlJavaTypeAdapter" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:Field" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="jaxb-intros:Method" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" use="required"/>
    </xsd:complexType>
    <xsd:element name="Class" type="jaxb-intros:Class">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">Java Top Level Class JAXB Annotation Introductions configuration.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="class-member-intro-config">
        <xsd:annotation>
           <xsd:documentation xml:lang="en">Java Class Member (Field, Method Constructor) JAXB Annotation Introductions configuration base type.</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element ref="jaxb-intros:XmlElement" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:XmlAttribute" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:XmlTransient" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:XmlID" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:XmlIDREF" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:XmlElementWrapper" minOccurs="0" maxOccurs="1"/>
            <xsd:element ref="jaxb-intros:XmlJavaTypeAdapter" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="name" use="required"/>
    </xsd:complexType>
    <xsd:element name="class-member-intro-config" abstract="true" />

    <xsd:complexType name="Field">
        <xsd:complexContent>
            <xsd:extension base="jaxb-intros:class-member-intro-config" />
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:element name="Field" type="jaxb-intros:Field" substitutionGroup="jaxb-intros:class-member-intro-config">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">Java Class Field JAXB Annotation Introductions configuration.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="Method">
        <xsd:complexContent>
            <xsd:extension base="jaxb-intros:class-member-intro-config" />
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:element name="Method" type="jaxb-intros:Method" substitutionGroup="jaxb-intros:class-member-intro-config">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">Java Class Method JAXB Annotation Introductions configuration.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="XmlAccessorType">
        <xsd:attribute name="value" use="optional" default="NONE">
            <xsd:simpleType>
                <xsd:restriction base="xsd:NMTOKEN">
                    <xsd:enumeration value="PROPERTY"/>
                    <xsd:enumeration value="FIELD"/>
                    <xsd:enumeration value="PUBLIC_MEMBER"/>
                    <xsd:enumeration value="NONE"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
    <xsd:element name="XmlAccessorType" type="jaxb-intros:XmlAccessorType" />

    <xsd:complexType name="XmlRootElement">
        <xsd:attribute name="namespace" use="optional" default="##default"/>
        <xsd:attribute name="name" use="optional" default="##default"/>
    </xsd:complexType>
    <xsd:element name="XmlRootElement" type="jaxb-intros:XmlRootElement"/>

    <xsd:complexType name="XmlType">
        <xsd:attribute name="name" use="optional" default="##default"/>
        <xsd:attribute name="propOrder" use="optional" default=""/>
        <xsd:attribute name="namespace" use="optional" default="##default"/>
        <xsd:attribute name="factoryClass" use="optional"/>
        <xsd:attribute name="factoryMethod" use="optional" default=""/>
    </xsd:complexType>
    <xsd:element name="XmlType" type="jaxb-intros:XmlType">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">JAXB 'XmlType' Annotation Introduction configuration.</xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="XmlElement">
        <xsd:attribute name="name" use="optional" default="##default"/>
        <xsd:attribute name="nillable" type="xsd:boolean" use="optional" default="false"/>
        <xsd:attribute name="required" type="xsd:boolean" use="optional" default="false"/>
        <xsd:attribute name="namespace" use="optional" default="##default"/>
        <xsd:attribute name="defaultValue" use="optional"/>
        <xsd:attribute name="type" use="optional"/>
    </xsd:complexType>
    <xsd:element name="XmlElement" type="jaxb-intros:XmlElement">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">JAXB 'XmlElement' Annotation Introduction configuration.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="XmlAttribute">
        <xsd:attribute name="name" use="optional" default="##default"/>
        <xsd:attribute name="required" type="xsd:boolean" use="optional" default="false"/>
        <xsd:attribute name="namespace" use="optional" default="##default"/>
    </xsd:complexType>
    <xsd:element name="XmlAttribute" type="jaxb-intros:XmlAttribute">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">JAXB 'XmlAttribute' Annotation Introduction configuration.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="XmlTransient">
    </xsd:complexType>
    <xsd:element name="XmlTransient" type="jaxb-intros:XmlTransient">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">JAXB 'XmlTransient' Annotation Introduction configuration.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="XmlID">
    </xsd:complexType>
    <xsd:element name="XmlID" type="jaxb-intros:XmlID">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">JAXB 'XmlID' Annotation Introduction configuration.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="XmlIDREF">
    </xsd:complexType>
    <xsd:element name="XmlIDREF" type="jaxb-intros:XmlIDREF">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">JAXB 'XmlIDREF' Annotation Introduction configuration.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="XmlElementWrapper">
    	<xsd:attribute name="name" use="optional" default="##default" />
    	<xsd:attribute name="namespace" use="optional" default="##default" />
    	<xsd:attribute name="required" use="optional" type="xsd:boolean" default="false" />
    	<xsd:attribute name="nillable" use="optional" type="xsd:boolean" default="false"  />
    </xsd:complexType>
    <xsd:element name="XmlElementWrapper" type="jaxb-intros:XmlElementWrapper">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">JAXB 'XmlElementWrapper' Annotation Introduction configuration.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>
    <xsd:complexType name="XmlJavaTypeAdapter">
    	<xsd:attribute name="value" use="required" />
    	<xsd:attribute name="type" use="optional" />
    </xsd:complexType>
    <xsd:element name="XmlJavaTypeAdapter" type="jaxb-intros:XmlJavaTypeAdapter">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">JAXB 'XmlJavaTypeAdapter' Annotation Introduction configuration.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

</xsd:schema>

=== pouncilt/ws-spring-restful-demo/src/main/resources/spring/jaxb-intros-marshaller-mapping.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<jaxb-intros xmlns="http://www.jboss.org/xsd/jaxb/intros"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.jboss.org/xsd/jaxb/intros http://anonsvn.jboss.org/repos/jbossws/projects/jaxbintros/trunk/src/main/resources/jaxb-intros.xsd">


    <Class name="com.pouncilt.pricing.model.BasePricingLabelCount">
        <XmlAccessorType value="FIELD"/>
        <XmlTransient/>
        <Field name="locationNumber">
            <XmlElement name="locationNumber" required="true" namespace="http://www.pouncilt.com/pricing/pricinglabels/model"/>
        </Field>
    </Class>
    <Class name="com.pouncilt.pricing.model.CorporatePricingLabelCount">
        <XmlAccessorType value="FIELD"/>
        <XmlType propOrder="{'locationNumber', 'divisionPricingLabelCounts'}"/>
        <XmlRootElement name="corporatePricingLabelCount" namespace="http://www.pouncilt.com/pricing/pricinglabels/model"/>
        <Field name="divisionPricingLabelCounts">
            <XmlElement name="divisionPricingLabelCounts"  namespace="http://www.pouncilt.com/pricing/pricinglabels/model"/>
            <XmlJavaTypeAdapter value="com.pouncilt.pricing.model.jaxb.adapters.DivisionPricingLabelCountMapAdapter"/>
        </Field>
    </Class>
    <Class name="com.pouncilt.pricing.model.DivisionPricingLabelCount">
        <XmlAccessorType value="FIELD"/>
        <XmlType propOrder="{'locationNumber', 'regionPricingLabelCounts'}"/>
        <Field name="regionPricingLabelCounts">
            <XmlElement name="regionPricingLabelCounts" namespace="http://www.pouncilt.com/pricing/pricinglabels/model"/>
            <XmlJavaTypeAdapter value="com.pouncilt.pricing.model.jaxb.adapters.RegionPricingLabelCountMapAdapter"/>
        </Field>
    </Class>
    <Class name="com.pouncilt.pricing.model.RegionPricingLabelCount">
        <XmlAccessorType value="FIELD"/>
        <XmlType propOrder="{'locationNumber', 'districtPricingLabelCounts'}"/>
        <Field name="districtPricingLabelCounts">
            <XmlElement name="districtPricingLabelCounts" namespace="http://www.pouncilt.com/pricing/pricinglabels/model"/>
            <XmlJavaTypeAdapter value="com.pouncilt.pricing.model.jaxb.adapters.DistrictPricingLabelCountMapAdapter"/>
        </Field>
    </Class>
    <Class name="com.pouncilt.pricing.model.DistrictPricingLabelCount">
        <XmlAccessorType value="FIELD"/>
        <XmlType propOrder="{'locationNumber', 'storePricingLabelCounts'}"/>
        <Field name="storePricingLabelCounts">
            <XmlElement name="storePricingLabelCounts" namespace="http://www.pouncilt.com/pricing/pricinglabels/model"/>
            <XmlJavaTypeAdapter value="com.pouncilt.pricing.model.jaxb.adapters.StorePricingLabelCountMapAdapter"/>
        </Field>
    </Class>
    <Class name="com.pouncilt.pricing.model.StorePricingLabelCount">
        <XmlAccessorType value="FIELD"/>
        <XmlType propOrder="{'locationNumber', 'labelCount'}"/>
        <Field name="labelCount">
            <XmlElement name="labelCount" required="true" namespace="http://www.pouncilt.com/pricing/pricinglabels/model"/>
        </Field>
    </Class>
</jaxb-intros>
